name: branch-protection

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: actions-rust-lang/setup-rust-toolchain@fb51252c7ba57d633bc668f941da052e410add48
        with:
          components: clippy
      - run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev pkg-config
      - run: cargo clippy --no-deps -- -D warnings

  test-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: actions-rust-lang/setup-rust-toolchain@fb51252c7ba57d633bc668f941da052e410add48
      - run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev pkg-config
      - run: cargo test --bin subscriber

  lint-c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - run: clang-format --dry-run --Werror embedded-workspace/peripheral-notify/src/*.c
      - run: clang-format --dry-run --Werror embedded-workspace/peripheral-notify/src/*.h
      - run: clang-format --dry-run --Werror embedded-workspace/peripheral-periodic/src/*.c
      - run: clang-format --dry-run --Werror embedded-workspace/peripheral-periodic/src/*.h
      - run: clang-format --dry-run --Werror embedded-workspace/peripheral-beacon/src/*.c
      - run: clang-format --dry-run --Werror embedded-workspace/peripheral-beacon/src/*.h

  check-success:
    runs-on: ubuntu-latest
    needs:
      - lint-rust
      - test-rust
      - lint-c
    steps:
      - run: echo true
